#ifndef ENCODER_SHOOTER_INPUT_H
#define ENCODER_SHOOTER_INPUT_H

/*
ROBOT ORIENTATION
         FRONT
    MOTOR1  MOTOR2  (2WD/ACKERMANN)
    MOTOR3  MOTOR4  (4WD/MECANUM)
         BACK
*/

// INVERT ENCODER DIRECTIONS
#define ENCODER1_INV true
#define ENCODER2_INV false


#define ENCODER1_INCRIMENT 32
#define ENCODER1_PIN_A 33
#define ENCODER1_PIN_B 25

#define ENCODER2_INCRIMENT 26
#define ENCODER2_PIN_A 27
#define ENCODER2_PIN_B 14


#define ENCODER1_PULSES_PER_REVOLUTION 600
#define ENCODER2_PULSES_PER_REVOLUTION 600


#endif