#ifndef ENCODER_INPUT_TEENSY_H
#define ENCODER_INPUT_TEENSY_H

/*
ROBOT ORIENTATION
         FRONT
    MOTOR1  MOTOR2  (2WD/ACKERMANN)
    MOTOR3  MOTOR4  (4WD/MECANUM)
         BACK
*/

// INVERT ENCODER DIRECTIONS
#define ENCODER1_INV true
#define ENCODER2_INV false
#define ENCODER3_INV true 
#define ENCODER4_INV false

#define ENCODER1_INCRIMENT 23
#define ENCODER1_PIN_A 22
#define ENCODER1_PIN_B 21

#define ENCODER2_INCRIMENT 20
#define ENCODER2_PIN_A 17
#define ENCODER2_PIN_B 16

#define ENCODER3_INCRIMENT 15
#define ENCODER3_PIN_A 14  //22 
#define ENCODER3_PIN_B 41  //21

#define ENCODER4_INCRIMENT 40
#define ENCODER4_PIN_A 39
#define ENCODER4_PIN_B 38

#endif